### ISSUE TITLE
bug 关于影子状态更新的问题

### ISSUE THREAD

**Issue by 362115815** [labuladong/fucking-algorithm#259]
你好，我发现如下文章有 bug（点击文字可跳转到相关文章）：

[动态规划系列/动态规划之KMP字符匹配算法.md](https://github.com/labuladong/fucking-algorithm/blob/master/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%B3%BB%E5%88%97/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E4%B9%8BKMP%E5%AD%97%E7%AC%A6%E5%8C%B9%E9%85%8D%E7%AE%97%E6%B3%95.md)

问题描述：

![11587047215_ pic_hd](https://user-images.githubusercontent.com/4704786/79468788-f4fa0400-8031-11ea-99bb-62f5d91f2e1a.jpg)

我的理解是只有当j=0时 dp[0][pat.charAt(j)]=1 才成立， 其余情况都是0， 那下面当j循环中j是从1 开始的，这样X更新时，永远取不到1 ，无法前进，是我理解有问题吗？

**Comment by yyy20119** [comment]
当j=0时 dp[0][pat.charAt(j)]=1这句话没问题。

但后面只要遍历的时候pat.charAt(j)和pat.charAt(0)相等，即遍历到的字符和第一个字符相同时，就能取到1，进而更新X。

**Comment by codroc** [comment]
你的理解有误，不是只有当j=0时，dp[0][pat.charAt(j)]=1, 二维数组 dp 的列是字母而非数字，所以，假设pat.charAt(0) = 'A'， 那么当 j 取到其他值时， pat.charAt(j) = 'A'仍然可能成立。

**Comment by XXS122** [comment]
哥&nbsp; 你回复错了吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"codroc"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 下午2:40
收件人:&nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)





 
你的理解有误，不是只有当j=0时，dp[0][pat.charAt(j)]=1, 二维数组 dp 的列是字母而非数字，所以，假设pat.charAt(0) = 'A'， 那么当 j 取到其他值时， pat.charAt(j) = 'A'仍然可能成立。

**Comment by nnt370** [comment]
为啥我总是能收到邮件，我并不想接收邮件

**Comment by nnt370** [comment]
不能单独回复吗？？？？！！！！！不想总是收到邮件




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XXS122"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 下午2:44
收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)





 哥&amp;nbsp; 你回复错了吧 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&quot;codroc&quot;<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月23日(星期四) 下午2:40 
 收件人:&amp;nbsp;&quot;labuladong/fucking-algorithm&quot;<fucking-algorithm@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259) 
 
 
 
 
 
   
 你的理解有误，不是只有当j=0时，dp[0][pat.charAt(j)]=1, 二维数组 dp 的列是字母而非数字，所以，假设pat.charAt(0) = &#39;A&#39;， 那么当 j 取到其他值时， pat.charAt(j) = &#39;A&#39;仍然可能成立。 
   
 — 
 You are receiving this because you are subscribed to this thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by XXS122** [comment]
兄弟，我没给你发邮件啊，是你给我发的什么影子状态更新问题解答，我只是在github上面关注了你，然后就收到了你的邮件




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nnt370"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 下午2:45
收件人:&nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送:&nbsp;"1396870564"<1396870564@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)





 
为啥我总是能收到邮件，我并不想接收邮件

**Comment by TAOSHss** [comment]
什么鬼啊



---原始邮件---
发件人: "nnt370"<notifications@github.com&gt;
发送时间: 2020年4月23日(星期四) 下午2:48
收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)




 不能单独回复吗？？？？！！！！！不想总是收到邮件 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "XXS122"<notifications@github.com&amp;gt;;  
 发送时间: 2020年4月23日(星期四) 下午2:44 
 收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;;  
 主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259) 
 
 
 
 
 
  哥&amp;amp;nbsp; 你回复错了吧  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;&amp;quot;codroc&amp;quot;<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年4月23日(星期四) 下午2:40  
  收件人:&amp;amp;nbsp;&amp;quot;labuladong/fucking-algorithm&amp;quot;<fucking-algorithm@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;&amp;quot;Subscribed&amp;quot;<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)  
   
   
   
   
   
     
  你的理解有误，不是只有当j=0时，dp[0][pat.charAt(j)]=1, 二维数组 dp 的列是字母而非数字，所以，假设pat.charAt(0) = &amp;#39;A&amp;#39;， 那么当 j 取到其他值时， pat.charAt(j) = &amp;#39;A&amp;#39;仍然可能成立。  
     
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 &amp;mdash;

**Comment by lzh1043060917** [comment]
我也是关注了这个项目，然后一直收到邮件。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XXS122"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 下午2:48
收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)





 兄弟，我没给你发邮件啊，是你给我发的什么影子状态更新问题解答，我只是在github上面关注了你，然后就收到了你的邮件 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"nnt370"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月23日(星期四) 下午2:45 
 收件人:&amp;nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"1396870564"<1396870564@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259) 
 
 
 
 
 
   
 为啥我总是能收到邮件，我并不想接收邮件

**Comment by saikei** [comment]
建议大家watch时候只关注release

**Comment by lzh1043060917** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TAOSHss"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 下午2:49
收件人:&nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)





 什么鬼啊 
 
 
 
 ---原始邮件--- 
 发件人: "nnt370"<notifications@github.com&amp;gt; 
 发送时间: 2020年4月23日(星期四) 下午2:48 
 收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259) 
 
 
 
 
  不能单独回复吗？？？？！！！！！不想总是收到邮件  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "XXS122"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年4月23日(星期四) 下午2:44  
  收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;amp;gt;;   
  抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;   
  主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)  
   
   
   
   
   
   哥&amp;amp;amp;nbsp; 你回复错了吧   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;&amp;amp;quot;codroc&amp;amp;quot;<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年4月23日(星期四) 下午2:40   
   收件人:&amp;amp;amp;nbsp;&amp;amp;quot;labuladong/fucking-algorithm&amp;amp;quot;<fucking-algorithm@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;&amp;amp;quot;Subscribed&amp;amp;quot;<subscribed@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)   
     
     
     
     
     
       
   你的理解有误，不是只有当j=0时，dp[0][pat.charAt(j)]=1, 二维数组 dp 的列是字母而非数字，所以，假设pat.charAt(0) = &amp;amp;#39;A&amp;amp;#39;， 那么当 j 取到其他值时， pat.charAt(j) = &amp;amp;#39;A&amp;amp;#39;仍然可能成立。   
       
   —   
   You are receiving this because you are subscribed to this thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
  &amp;amp;mdash;

**Comment by XXS122** [comment]
哈哈哈&nbsp; 我也不知道怎么回事，，加个微信啊，第一次和别人在邮箱聊天挺有意思，hyj13796002437


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"梁自豪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 下午2:49
收件人:&nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送:&nbsp;"1396870564"<1396870564@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)





 我也是关注了这个项目，然后一直收到邮件。。。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "XXS122"<notifications@github.com&amp;gt;;  
 发送时间: 2020年4月23日(星期四) 下午2:48 
 收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;;  
 主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259) 
 
 
 
 
 
  兄弟，我没给你发邮件啊，是你给我发的什么影子状态更新问题解答，我只是在github上面关注了你，然后就收到了你的邮件  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"nnt370"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年4月23日(星期四) 下午2:45  
  收件人:&amp;amp;nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"1396870564"<1396870564@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)  
   
   
   
   
   
     
  为啥我总是能收到邮件，我并不想接收邮件

**Comment by z573419235** [comment]
山东省对方水电费水电费水电费水电费水电费水电费水电费水电费等所发生的发送到发送到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nnt370"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 下午2:47
收件人:&nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)





 不能单独回复吗？？？？！！！！！不想总是收到邮件 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "XXS122"<notifications@github.com&amp;gt;;  
 发送时间: 2020年4月23日(星期四) 下午2:44 
 收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;gt;;  
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;;  
 主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259) 
 
 
 
 
 
  哥&amp;amp;nbsp; 你回复错了吧  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;&amp;quot;codroc&amp;quot;<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年4月23日(星期四) 下午2:40  
  收件人:&amp;amp;nbsp;&amp;quot;labuladong/fucking-algorithm&amp;quot;<fucking-algorithm@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;&amp;quot;Subscribed&amp;quot;<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)  
   
   
   
   
   
     
  你的理解有误，不是只有当j=0时，dp[0][pat.charAt(j)]=1, 二维数组 dp 的列是字母而非数字，所以，假设pat.charAt(0) = &amp;#39;A&amp;#39;， 那么当 j 取到其他值时， pat.charAt(j) = &amp;#39;A&amp;#39;仍然可能成立。  
     
  —  
  You are receiving this because you are subscribed to this thread.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 &amp;mdash;

**Comment by bj-shu** [comment]
同学们666



---原始邮件---
发件人: "灰灰"<notifications@github.com&gt;
发送时间: 2020年4月23日(周四) 下午3:06
收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)




 山东省对方水电费水电费水电费水电费水电费水电费水电费水电费等所发生的发送到发送到 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"nnt370"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年4月23日(星期四) 下午2:47 
 收件人:&amp;nbsp;"labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259) 
 
 
 
 
 
  不能单独回复吗？？？？！！！！！不想总是收到邮件  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "XXS122"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年4月23日(星期四) 下午2:44  
  收件人: "labuladong/fucking-algorithm"<fucking-algorithm@noreply.github.com&amp;amp;gt;;   
  抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;   
  主题: Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)  
   
   
   
   
   
   哥&amp;amp;amp;nbsp; 你回复错了吧   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;&amp;amp;quot;codroc&amp;amp;quot;<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年4月23日(星期四) 下午2:40   
   收件人:&amp;amp;amp;nbsp;&amp;amp;quot;labuladong/fucking-algorithm&amp;amp;quot;<fucking-algorithm@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;&amp;amp;quot;Subscribed&amp;amp;quot;<subscribed@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [labuladong/fucking-algorithm] bug 关于影子状态更新的问题 (#259)   
     
     
     
     
     
       
   你的理解有误，不是只有当j=0时，dp[0][pat.charAt(j)]=1, 二维数组 dp 的列是字母而非数字，所以，假设pat.charAt(0) = &amp;amp;#39;A&amp;amp;#39;， 那么当 j 取到其他值时， pat.charAt(j) = &amp;amp;#39;A&amp;amp;#39;仍然可能成立。   
       
   —   
   You are receiving this because you are subscribed to this thread.   
   Reply to this email directly, view it on GitHub, or unsubscribe.   
  &amp;amp;mdash;

**Comment by yyy20119** [comment]
笑死。。
github强大的邮箱提醒功能
